### PR TITLE
Standardize format of changelog across repos

### PR DESCRIPTION
**Pull request by JPrause**

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by djberg96** [comment]
@JPrause I don't know that the way I've written it now is actually supported by markdown.

Also, it seems we don't have a "documentation" label for this project.

**Comment by JPrause** [comment]
Thanks @dberg96
Gotcha,....perhaps we can work this out when you're here.
There are other similar repos, so it'd be helpful.

**Comment by djberg96** [comment]
I'd set the milestone, but there don't appear to be any to choose from. Anyway, merging.

**Pull request merged**
